---
version: "3.9"

services:

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      PUID: $app_pgid
      PGID: $app_pgid
      TZ: $app_tz
    volumes:
      - $app_dir_conf:/config
      - $app_dir_data:/data

