---
version: "3.9"

services:
  qbittorrent:
    image: ${app_image:-${app_image_name}:${app_image_version}}
    restart: unless-stopped
    environment:
      - PUID=$app_puid
      - PGID=$app_pgid
      - TZ=$app_tz
      - WEBUI_PORT=$app_port
    volumes:
      - $app_dir_conf:/config
        #- $app_dir_data:/data/torrents
        #- $app_dir_data:/downloads
      - $app_dir_data:/data
      - $app_dir_template/frontends:/frontends
