---
version: "3.9"

services:

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    environment:
      PUID: $app_pgid
      PGID: $app_pgid
      TZ: $app_tz
      BASE_URL: /
    volumes:
      - $app_dir_conf:/config

