---
version: "3.9"

services:

  prowlarr:
    #    image: lscr.io/linuxserver/prowlarr:latest
    image: ${app_image:-${app_image_name}:${app_image_version}}
    restart: unless-stopped
    environment:
      PUID: $app_pgid
      PGID: $app_pgid
      TZ: $app_tz
    volumes:
      - $app_dir_conf:/config

