---
version: "3.9"

services:
  homer:
    image: b4bz/homer
    restart: unless-stopped
    environment:
      INIT_ASSETS: 1
      PUID: $app_pgid
      PGID: $app_pgid
      TZ: $app_tz
    volumes:
      - $app_dir_data:/www/assets/
