---
version: "3.9"

services:

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    security_opt:
      - seccomp:unconfined #optional
    environment:
      PUID: $app_pgid
      PGID: $app_pgid
      TZ: $app_tz
        #PASSWORD: admin #optional
      CLI_ARGS: #optional
    volumes:
      - $app_dir_conf:/config
      - $app_dir_share:/config/Calibre Library
        #ports:
        #  - 8080:8080
        #  - 8181:8181
        #  - 8081:8081
    restart: unless-stopped
