---
version: "3.9"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      PUID: $app_pgid
      PGID: $app_pgid
      TZ: $app_tz
      # JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
      JELLYFIN_PublishedServerUrl: $app_fqdn

    volumes:
      - $app_dir_conf:/config
      - $app_dir_data:/data

#    ports:
#      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional

