---
version: "3.9"

services:
  lidarr:
    image: ${app_image}
    restart: unless-stopped
    environment:
      PUID: $app_pgid
      PGID: $app_pgid
      TZ: $app_tz
    volumes:
      - $app_dir_conf:/config
      - $app_dir_data:/data
