version: '3.7'

services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    environment:
      - PUID=$app_puid
      - PGID=$app_pgid
      - TZ=$app_tz
      - DB_TYPE=sqlite #optional
    volumes:
      - $app_dir_conf:/config
      - $app_dir_data:/data
    restart: unless-stopped
